/**
 * Chorus Workflow <-> Drawflow graph converters.
 *
 * Drawflow's on-disk format is a nested object under `drawflow.Home.data`,
 * where each node is keyed by its numeric Drawflow id. Chorus Workflows
 * (packages/core/src/schemas.ts) carry Node[] + Connection[] arrays with
 * integration/operation/config metadata.
 *
 * These helpers round-trip the graph between the two representations so
 * the HTML editor generated by `chorus ui --editor` can:
 *   1. Load an existing Chorus workflow into a Drawflow canvas (via
 *      chorusToDrawflow).
 *   2. Export whatever the user built back into Chorus shape (via
 *      drawflowToChorus).
 *
 * Design constraints:
 *   - Pure functions, no I/O — call sites handle persistence.
 *   - Stable node-id <-> Drawflow-number mapping preserved in node.data so
 *     a round-trip does not renumber existing Chorus ids.
 *   - Connection `when` expressions survive the round-trip (stored on the
 *     connection object; we index by source+target since Drawflow's native
 *     edge format has no per-edge payload).
 *   - The implementation mirrors the JS copy inlined in editor-template.html
 *     exactly so the transform behaves identically in-browser and in Node.
 */
import type { Workflow, Node, Connection } from "@delightfulchorus/core";

/**
 * The subset of Drawflow's export shape we rely on. Drawflow itself emits
 * { drawflow: { Home: { data: {...} } } }; we accept either the full wrap
 * or the `Home.data` node map directly for test ergonomics.
 */
export interface DrawflowNodeInputs {
  [portName: string]: {
    connections: Array<{ node: string; input: string }>;
  };
}

export interface DrawflowNodeOutputs {
  [portName: string]: {
    connections: Array<{ node: string; output: string }>;
  };
}

export interface DrawflowNode {
  id: number;
  name: string;
  data: Record<string, unknown>;
  class: string;
  html: string;
  typenode: boolean | string;
  inputs: DrawflowNodeInputs;
  outputs: DrawflowNodeOutputs;
  pos_x: number;
  pos_y: number;
}

export interface DrawflowGraph {
  drawflow: {
    Home: {
      data: Record<string, DrawflowNode>;
    };
  };
}

/**
 * Metadata we stash inside each Drawflow node's `data` field so the
 * inverse transform can reconstruct Chorus ids and connection predicates
 * without being able to extend Drawflow's edge format.
 */
interface ChorusNodeExtras {
  chorusNodeId: string;
  integration: string;
  operation: string;
  config?: Record<string, unknown>;
  inputs?: Record<string, unknown>;
  onError?: Node["onError"];
  retry?: Node["retry"];
}

/**
 * Metadata we stash on the graph root (as a synthetic "chorus-meta" node
 * that Drawflow renders off-canvas) to preserve Workflow-level fields like
 * id / name / version / trigger and per-connection `when` expressions.
 *
 * We keep this as a hidden node (typenode="hidden") rather than a
 * top-level drawflow root field because Drawflow drops unknown root keys
 * on reimport.
 */
interface ChorusGraphMeta {
  chorusMeta: true;
  workflowId: string;
  workflowName: string;
  version: number;
  active: boolean;
  trigger: Workflow["trigger"];
  createdAt: string;
  updatedAt: string;
  /** `from-to-idx` -> when expression. idx lets us carry parallel edges. */
  whenMap: Record<string, string>;
}

const META_NODE_ID = 0; // reserved slot; real nodes start at 1
const META_NODE_CLASS = "chorus-meta";

// ── Chorus -> Drawflow ──────────────────────────────────────────────────────

/**
 * Convert a Chorus Workflow into a Drawflow graph ready for
 * `editor.import(...)`. Node positions are laid out in a simple left-to-right
 * column grid: nodes with no inbound edges go in column 0, each reachable
 * node sits one column past its earliest predecessor.
 *
 * Inline config is rendered inside the node's HTML as `df-<field>` inputs;
 * Drawflow auto-binds those inputs to `node.data.<field>`.
 */
export function chorusToDrawflow(workflow: Workflow): DrawflowGraph {
  const data: Record<string, DrawflowNode> = {};
  const idToNumber = new Map<string, number>();

  // Assign sequential numbers starting at 1 so META_NODE_ID (0) stays free.
  let next = 1;
  for (const n of workflow.nodes) {
    idToNumber.set(n.id, next);
    next += 1;
  }

  // Column-based layout. Root nodes (no inbound) get column 0; children get
  // one more than their first predecessor. Falls back to column 0 for
  // disconnected cycles (unlikely for a valid workflow but defensive).
  const columns = computeColumns(workflow);

  for (const n of workflow.nodes) {
    const num = idToNumber.get(n.id)!;
    const col = columns.get(n.id) ?? 0;
    const rowIndex = Array.from(columns.entries()).filter(
      ([, c]) => c === col,
    ).findIndex(([id]) => id === n.id);
    data[String(num)] = buildDrawflowNode(n, num, col, Math.max(rowIndex, 0), workflow, idToNumber);
  }

  // Connection wiring: each edge becomes an output connection on the source
  // and a mirrored input connection on the target (Drawflow requires both).
  const whenMap: Record<string, string> = {};
  const edgeCounter = new Map<string, number>(); // from|to -> count
  for (const c of workflow.connections) {
    const fromNum = idToNumber.get(c.from);
    const toNum = idToNumber.get(c.to);
    if (fromNum == null || toNum == null) continue; // dangling edge — skip
    const fromNode = data[String(fromNum)];
    const toNode = data[String(toNum)];
    if (!fromNode || !toNode) continue;
    // Drawflow names ports "output_1" / "input_1" by default (we only use one
    // per node; branches live as multiple outgoing connections on the same
    // port).
    fromNode.outputs.output_1!.connections.push({
      node: String(toNum),
      output: "input_1",
    });
    toNode.inputs.input_1!.connections.push({
      node: String(fromNum),
      input: "output_1",
    });
    if (c.when && c.when.length > 0) {
      const key = `${c.from}|${c.to}`;
      const idx = (edgeCounter.get(key) ?? 0);
      edgeCounter.set(key, idx + 1);
      whenMap[`${c.from}|${c.to}|${idx}`] = c.when;
    }
  }

  // Attach the graph-level meta node so drawflowToChorus can restore
  // id/name/trigger/when without losing information.
  const meta: ChorusGraphMeta = {
    chorusMeta: true,
    workflowId: workflow.id,
    workflowName: workflow.name,
    version: workflow.version,
    active: workflow.active,
    trigger: workflow.trigger,
    createdAt: workflow.createdAt,
    updatedAt: workflow.updatedAt,
    whenMap,
  };
  data[String(META_NODE_ID)] = {
    id: META_NODE_ID,
    name: META_NODE_CLASS,
    data: meta as unknown as Record<string, unknown>,
    class: META_NODE_CLASS,
    html: "",
    typenode: "hidden",
    inputs: {},
    outputs: {},
    pos_x: -9999,
    pos_y: -9999,
  };

  return { drawflow: { Home: { data } } };
}

/**
 * Simple longest-path layout: BFS from roots (no inbound edges). Each node
 * sits at `max(parent_column) + 1`. Nodes unreachable from any root fall
 * through to column 0, which keeps layouts stable for malformed graphs.
 */
function computeColumns(workflow: Workflow): Map<string, number> {
  const inbound = new Map<string, string[]>();
  for (const n of workflow.nodes) inbound.set(n.id, []);
  for (const c of workflow.connections) {
    const arr = inbound.get(c.to);
    if (arr) arr.push(c.from);
  }
  const columns = new Map<string, number>();
  // Topological visit via Kahn-ish: repeatedly assign column = max(parent)+1
  // for nodes whose parents are all assigned. Up to workflow.nodes.length
  // passes terminate for DAGs; cycles stop improving after one cycle.
  const remaining = new Set(workflow.nodes.map((n) => n.id));
  for (let pass = 0; pass < workflow.nodes.length + 1; pass += 1) {
    let changed = false;
    for (const id of Array.from(remaining)) {
      const parents = inbound.get(id) ?? [];
      const resolved = parents.every((p) => columns.has(p));
      if (parents.length === 0) {
        if (!columns.has(id)) {
          columns.set(id, 0);
          changed = true;
          remaining.delete(id);
        }
      } else if (resolved) {
        const max = Math.max(...parents.map((p) => columns.get(p)!));
        columns.set(id, max + 1);
        remaining.delete(id);
        changed = true;
      }
    }
    if (!changed) break;
  }
  // Anything left (cycle) pins to 0.
  for (const id of remaining) columns.set(id, 0);
  return columns;
}

/** Build one Drawflow node from a Chorus Node, with inline config inputs. */
function buildDrawflowNode(
  n: Node,
  num: number,
  col: number,
  row: number,
  _wf: Workflow,
  _idMap: Map<string, number>,
): DrawflowNode {
  const extras: ChorusNodeExtras = {
    chorusNodeId: n.id,
    integration: n.integration,
    operation: n.operation,
    config: n.config ?? {},
    inputs: n.inputs,
    onError: n.onError,
    retry: n.retry,
  };
  // Data payload that Drawflow will auto-sync with `df-*` inputs in the
  // rendered HTML. We expose the top-level config fields directly so users
  // can edit common values without a nested form.
  const data: Record<string, unknown> = { ...extras, ...flattenConfig(n.config ?? {}) };

  return {
    id: num,
    name: `${n.integration}.${n.operation}`,
    data,
    class: classNameFor(n.integration),
    html: renderNodeHtml(n),
    typenode: false,
    inputs: { input_1: { connections: [] } },
    outputs: { output_1: { connections: [] } },
    pos_x: 40 + col * 260,
    pos_y: 40 + row * 140,
  };
}

function classNameFor(integration: string): string {
  return `chorus-node chorus-${integration.replace(/[^a-z0-9-]/gi, "-")}`;
}

/**
 * Flatten a Chorus Node.config object into Drawflow-friendly scalar fields.
 * Only primitive values survive — nested objects stay in `data.config`
 * untouched (editing those requires the raw-JSON popover in the editor).
 */
function flattenConfig(config: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(config)) {
    if (typeof v === "string" || typeof v === "number" || typeof v === "boolean") {
      out[`cfg_${k}`] = v;
    }
  }
  return out;
}

/**
 * Render the inner HTML for a node. Kept minimal so it stays legible in a
 * generated 400-line template. `df-*` attributes auto-wire to `node.data.*`.
 */
function renderNodeHtml(n: Node): string {
  const header = `<div class="df-title">${escapeHtml(n.integration)}<span class="df-op">.${escapeHtml(n.operation)}</span></div>`;
  const subtitle = `<div class="df-id">${escapeHtml(n.id)}</div>`;
  const configFields = Object.entries(n.config ?? {})
    .filter(
      ([, v]) => typeof v === "string" || typeof v === "number" || typeof v === "boolean",
    )
    .map(
      ([k, v]) =>
        `<label class="df-field"><span>${escapeHtml(k)}</span><input df-cfg_${escapeHtml(k)} type="text" value="${escapeHtmlAttr(String(v))}"></label>`,
    )
    .join("");
  return `${header}${subtitle}${configFields}`;
}

function escapeHtml(s: string): string {
  return s.replace(/[<>&"']/g, (c) => ({ "<": "&lt;", ">": "&gt;", "&": "&amp;", '"': "&quot;", "'": "&#39;" })[c]!);
}
function escapeHtmlAttr(s: string): string {
  return escapeHtml(s);
}

// ── Drawflow -> Chorus ──────────────────────────────────────────────────────

/**
 * Convert a Drawflow graph back into a Chorus Workflow, using the supplied
 * baseWorkflow for workflow-level fields (id, name, trigger, createdAt)
 * that Drawflow can't round-trip perfectly. If the graph carries a
 * chorus-meta node (written by chorusToDrawflow), we prefer its metadata.
 */
export function drawflowToChorus(
  graph: DrawflowGraph,
  baseWorkflow: Workflow,
): Workflow {
  const data = graph.drawflow?.Home?.data ?? {};
  const entries = Object.entries(data);

  // Extract the meta node (if present); drop it before we build node list.
  let meta: ChorusGraphMeta | null = null;
  for (const [, node] of entries) {
    const maybe = node.data as { chorusMeta?: boolean } | undefined;
    if (maybe?.chorusMeta) {
      meta = node.data as unknown as ChorusGraphMeta;
      break;
    }
  }

  const nodes: Node[] = [];
  const numToChorusId = new Map<string, string>();

  for (const [num, node] of entries) {
    if ((node.data as { chorusMeta?: boolean })?.chorusMeta) continue;
    const extras = node.data as ChorusNodeExtras & Record<string, unknown>;

    // Prefer the Chorus id stashed in extras; fall back to the Drawflow
    // name (in "integration.operation" form plus numeric suffix) if a new
    // node was dragged onto the canvas without a Chorus id.
    const chorusId = extras.chorusNodeId ?? `node-${num}`;
    numToChorusId.set(num, chorusId);

    // Merge flattened cfg_* fields back into config.
    const config: Record<string, unknown> = { ...(extras.config ?? {}) };
    for (const [k, v] of Object.entries(extras)) {
      if (k.startsWith("cfg_")) {
        const key = k.slice("cfg_".length);
        config[key] = v;
      }
    }

    // Parse integration.operation from the node's `name` if extras missing
    // (happens when the user drags a new integration onto the canvas).
    let integration = extras.integration;
    let operation = extras.operation;
    if ((!integration || !operation) && typeof node.name === "string" && node.name.includes(".")) {
      const dot = node.name.indexOf(".");
      integration = integration || node.name.slice(0, dot);
      operation = operation || node.name.slice(dot + 1);
    }

    const out: Node = {
      id: chorusId,
      integration: integration ?? "http-generic",
      operation: operation ?? "request",
      config,
      onError: extras.onError ?? "retry",
    };
    if (extras.inputs && Object.keys(extras.inputs).length > 0) out.inputs = extras.inputs;
    if (extras.retry) out.retry = extras.retry;
    nodes.push(out);
  }

  // Rebuild connections by walking Drawflow outputs. Each node output
  // lists its downstream nodes by Drawflow numeric id — we map back to
  // Chorus ids via numToChorusId.
  const connections: Connection[] = [];
  const edgeCounter = new Map<string, number>();
  for (const [num, node] of entries) {
    if ((node.data as { chorusMeta?: boolean })?.chorusMeta) continue;
    const fromId = numToChorusId.get(num);
    if (!fromId) continue;
    const outputs = node.outputs ?? {};
    for (const port of Object.values(outputs)) {
      for (const conn of port.connections ?? []) {
        const toId = numToChorusId.get(conn.node);
        if (!toId) continue;
        const edge: Connection = { from: fromId, to: toId };
        const key = `${fromId}|${toId}`;
        const idx = edgeCounter.get(key) ?? 0;
        edgeCounter.set(key, idx + 1);
        const whenKey = `${fromId}|${toId}|${idx}`;
        if (meta?.whenMap?.[whenKey]) edge.when = meta.whenMap[whenKey];
        connections.push(edge);
      }
    }
  }

  const nowIso = new Date().toISOString();
  // Prefer meta values (first-class round-trip) but let the base workflow
  // supply anything meta is missing (e.g., first-time export from a
  // hand-built canvas that lacks the hidden meta node).
  const result: Workflow = {
    id: meta?.workflowId ?? baseWorkflow.id,
    name: meta?.workflowName ?? baseWorkflow.name,
    version: meta?.version ?? baseWorkflow.version,
    active: meta?.active ?? baseWorkflow.active,
    trigger: meta?.trigger ?? baseWorkflow.trigger,
    nodes,
    connections,
    createdAt: meta?.createdAt ?? baseWorkflow.createdAt,
    updatedAt: nowIso,
  };
  return result;
}

/**
 * Produce the minified single-file JavaScript body that the generated
 * editor HTML inlines. Kept as a constant export so tests can verify the
 * browser copy mirrors the Node copy line-for-line (modulo type
 * annotations).
 *
 * The browser version is plain JS, no imports. It's small (~3 KB) so we
 * inline it literally rather than transpile the TS source at generation
 * time.
 */
export const INLINED_TRANSFORM_JS = `
// Chorus <-> Drawflow transform (inlined for editor HTML).
// Mirrors packages/cli/src/lib/drawflow-transform.ts — edit both together.
(function(global){
  function escapeHtml(s){return String(s).replace(/[<>&"']/g,function(c){return({"<":"&lt;",">":"&gt;","&":"&amp;",'"':"&quot;","'":"&#39;"})[c]});}
  function flattenConfig(cfg){var out={};for(var k in cfg){var v=cfg[k];if(typeof v==="string"||typeof v==="number"||typeof v==="boolean"){out["cfg_"+k]=v;}}return out;}
  function renderNodeHtml(n){var header='<div class="df-title">'+escapeHtml(n.integration)+'<span class="df-op">.'+escapeHtml(n.operation)+'</span></div>';
    var subtitle='<div class="df-id">'+escapeHtml(n.id)+'</div>';
    var body=Object.keys(n.config||{}).filter(function(k){var v=(n.config||{})[k];return typeof v==="string"||typeof v==="number"||typeof v==="boolean";})
      .map(function(k){var v=(n.config||{})[k];return '<label class="df-field"><span>'+escapeHtml(k)+'</span><input df-cfg_'+escapeHtml(k)+' type="text" value="'+escapeHtml(String(v))+'"></label>';}).join("");
    return header+subtitle+body;}
  function classNameFor(i){return "chorus-node chorus-"+String(i).replace(/[^a-z0-9-]/gi,"-");}
  function computeColumns(wf){var inbound={};wf.nodes.forEach(function(n){inbound[n.id]=[];});wf.connections.forEach(function(c){if(inbound[c.to])inbound[c.to].push(c.from);});
    var cols={};var remaining=new Set(wf.nodes.map(function(n){return n.id;}));
    for(var pass=0;pass<wf.nodes.length+1;pass++){var changed=false;Array.from(remaining).forEach(function(id){var parents=inbound[id]||[];var resolved=parents.every(function(p){return cols.hasOwnProperty(p);});
      if(parents.length===0){if(!cols.hasOwnProperty(id)){cols[id]=0;changed=true;remaining.delete(id);}}
      else if(resolved){var max=Math.max.apply(null,parents.map(function(p){return cols[p];}));cols[id]=max+1;remaining.delete(id);changed=true;}});
      if(!changed)break;}
    remaining.forEach(function(id){cols[id]=0;});return cols;}
  function chorusToDrawflow(wf){var data={};var idToNumber={};var next=1;
    wf.nodes.forEach(function(n){idToNumber[n.id]=next;next++;});
    var cols=computeColumns(wf);var rowByCol={};
    wf.nodes.forEach(function(n){
      var num=idToNumber[n.id];var col=cols[n.id]||0;if(rowByCol[col]==null)rowByCol[col]=0;var row=rowByCol[col]++;
      var extras={chorusNodeId:n.id,integration:n.integration,operation:n.operation,config:n.config||{},inputs:n.inputs,onError:n.onError,retry:n.retry};
      var flat=flattenConfig(n.config||{});
      var merged=Object.assign({},extras,flat);
      data[String(num)]={id:num,name:n.integration+"."+n.operation,data:merged,class:classNameFor(n.integration),html:renderNodeHtml(n),typenode:false,
        inputs:{input_1:{connections:[]}},outputs:{output_1:{connections:[]}},pos_x:40+col*260,pos_y:40+row*140};
    });
    var whenMap={};var counter={};
    wf.connections.forEach(function(c){var from=idToNumber[c.from];var to=idToNumber[c.to];if(!from||!to)return;
      data[String(from)].outputs.output_1.connections.push({node:String(to),output:"input_1"});
      data[String(to)].inputs.input_1.connections.push({node:String(from),input:"output_1"});
      if(c.when){var key=c.from+"|"+c.to;var idx=counter[key]||0;counter[key]=idx+1;whenMap[c.from+"|"+c.to+"|"+idx]=c.when;}});
    var meta={chorusMeta:true,workflowId:wf.id,workflowName:wf.name,version:wf.version,active:wf.active,trigger:wf.trigger,createdAt:wf.createdAt,updatedAt:wf.updatedAt,whenMap:whenMap};
    data["0"]={id:0,name:"chorus-meta",data:meta,class:"chorus-meta",html:"",typenode:"hidden",inputs:{},outputs:{},pos_x:-9999,pos_y:-9999};
    return {drawflow:{Home:{data:data}}};}
  function drawflowToChorus(graph,base){var data=(graph&&graph.drawflow&&graph.drawflow.Home&&graph.drawflow.Home.data)||{};
    var meta=null;Object.keys(data).forEach(function(k){if(data[k].data&&data[k].data.chorusMeta){meta=data[k].data;}});
    var nodes=[];var numToId={};
    Object.keys(data).forEach(function(num){var node=data[num];if(node.data&&node.data.chorusMeta)return;
      var ex=node.data||{};var chorusId=ex.chorusNodeId||"node-"+num;numToId[num]=chorusId;
      var config=Object.assign({},ex.config||{});Object.keys(ex).forEach(function(k){if(k.indexOf("cfg_")===0){config[k.slice(4)]=ex[k];}});
      var integration=ex.integration;var operation=ex.operation;
      if((!integration||!operation)&&typeof node.name==="string"&&node.name.indexOf(".")>=0){var dot=node.name.indexOf(".");integration=integration||node.name.slice(0,dot);operation=operation||node.name.slice(dot+1);}
      var out={id:chorusId,integration:integration||"http-generic",operation:operation||"request",config:config,onError:ex.onError||"retry"};
      if(ex.inputs&&Object.keys(ex.inputs).length>0)out.inputs=ex.inputs;
      if(ex.retry)out.retry=ex.retry;
      nodes.push(out);});
    var connections=[];var counter={};
    Object.keys(data).forEach(function(num){var node=data[num];if(node.data&&node.data.chorusMeta)return;
      var fromId=numToId[num];if(!fromId)return;
      var outputs=node.outputs||{};Object.keys(outputs).forEach(function(port){(outputs[port].connections||[]).forEach(function(conn){
        var toId=numToId[conn.node];if(!toId)return;
        var edge={from:fromId,to:toId};var key=fromId+"|"+toId;var idx=counter[key]||0;counter[key]=idx+1;
        var whenKey=fromId+"|"+toId+"|"+idx;if(meta&&meta.whenMap&&meta.whenMap[whenKey])edge.when=meta.whenMap[whenKey];
        connections.push(edge);});});});
    return {id:(meta&&meta.workflowId)||base.id,name:(meta&&meta.workflowName)||base.name,version:(meta&&meta.version)||base.version,
      active:meta?meta.active:base.active,trigger:(meta&&meta.trigger)||base.trigger,nodes:nodes,connections:connections,
      createdAt:(meta&&meta.createdAt)||base.createdAt,updatedAt:new Date().toISOString()};}
  global.chorusTransform={chorusToDrawflow:chorusToDrawflow,drawflowToChorus:drawflowToChorus};
})(typeof window!=="undefined"?window:globalThis);
`;
