/**
 * Generated by `chorus compose`.
 * Edit freely — re-running compose will NOT overwrite (errors if file exists).
 */
import type { Workflow } from "@delightfulchorus/core";

const workflow: Workflow = 
{
  "id": "linear-bug-digest",
  "name": "Daily Linear bug digest",
  "version": 1,
  "active": true,
  "trigger": {
    "type": "cron",
    "expression": "0 9 * * *",
    "timezone": "UTC"
  },
  "nodes": [
    {
      "id": "fetch-issues",
      "integration": "http-generic",
      "operation": "request",
      "config": {
        "url": "https://api.linear.app/graphql",
        "method": "POST",
        "headers": {
          "Content-Type": "application/json"
        },
        "body": {
          "query": "query BugIssues { issues(filter: { labels: { name: { eq: \"bug\" } } }, orderBy: createdAt) { nodes { id title url createdAt } } }"
        }
      },
      "onError": "retry"
    },
    {
      "id": "summarize",
      "integration": "llm-anthropic",
      "operation": "generate",
      "config": {
        "model": "claude-opus-4-7"
      },
      "inputs": {
        "prompt": "Summarize these Linear bug issues in 3 bullets:\n{{fetch-issues.body}}"
      },
      "onError": "retry"
    },
    {
      "id": "post",
      "integration": "slack-send",
      "operation": "postMessage",
      "config": {
        "channel": "#team"
      },
      "inputs": {
        "text": "{{summarize.text}}"
      },
      "onError": "retry"
    }
  ],
  "connections": [
    {
      "from": "fetch-issues",
      "to": "summarize"
    },
    {
      "from": "summarize",
      "to": "post"
    }
  ],
  "createdAt": "2026-04-22T09:00:00Z",
  "updatedAt": "2026-04-22T09:00:00Z"
}
;

export default workflow;
