/**
 * @chorus/mcp — generate
 *
 * Generate a standalone MCP server scaffold for a Chorus integration. The
 * emitted directory is self-contained: `npm install && npm start` runs it,
 * and it's registrable in Claude Desktop / Cursor / Zed via a one-liner
 * `.mcp.json` / `claude_desktop_config.json` block.
 *
 * Scaffold layout:
 *   mcp-servers/chorus-<integration>/
 *     package.json       — @chorus/mcp + @chorus-integrations/<name>
 *     index.js           — entrypoint: import both, call serveIntegration
 *     README.md          — how to wire into MCP clients
 *
 * Returned `configSnippet` is the exact `.mcp.json` block the user pastes
 * into their client's config.
 */
import path from "node:path";
import { mkdir, writeFile } from "node:fs/promises";

export interface GenerateMcpServerOptions {
  /** Integration name, e.g. "slack-send". */
  integration: string;
  /**
   * Output root. Defaults to `<cwd>/mcp-servers/chorus-<integration>/`.
   */
  outDir?: string;
  /**
   * Version of the generated scaffold's own package. Defaults to "0.1.0".
   * The dependency versions for @chorus/mcp and the integration package
   * are filled in at install time by the user's npm resolution.
   */
  scaffoldVersion?: string;
  /**
   * How to identify the integration package. Default:
   *   `@chorus-integrations/<integration>`
   * Override when the caller ships a custom-named integration.
   */
  integrationPackage?: string;
  /**
   * Optional description override for the scaffold's package.json. Falls
   * back to a generic "MCP server for the <integration> Chorus integration".
   */
  description?: string;
  /** Skip writing files and return the file contents (for tests). */
  dryRun?: boolean;
}

export interface GenerateMcpServerResult {
  /** Absolute path to the generated scaffold directory. */
  path: string;
  /**
   * JSON snippet to paste into a `.mcp.json` / `claude_desktop_config.json`.
   * Matches the MCP client registration shape (one entry under `mcpServers`).
   */
  configSnippet: string;
  /**
   * Files that were (or would have been) written. Exposed so tests can
   * assert on scaffold contents without hitting the filesystem.
   */
  files: Array<{ path: string; content: string }>;
}

/**
 * Generate an MCP server scaffold. Writes files under `outDir` unless
 * `dryRun: true`, then returns the scaffold path + config snippet for
 * integration into MCP clients.
 */
export async function generateMcpServer(
  opts: GenerateMcpServerOptions,
): Promise<GenerateMcpServerResult> {
  const integration = validateIntegrationName(opts.integration);
  const outDir =
    opts.outDir ??
    path.join(process.cwd(), "mcp-servers", `chorus-${integration}`);
  const scaffoldVersion = opts.scaffoldVersion ?? "0.1.0";
  const integrationPackage =
    opts.integrationPackage ?? `@chorus-integrations/${integration}`;
  const description =
    opts.description ??
    `MCP server exposing the ${integration} Chorus integration. ` +
      `Generated by @chorus/mcp.`;

  const files = [
    {
      path: path.join(outDir, "package.json"),
      content: renderPackageJson({
        integration,
        scaffoldVersion,
        integrationPackage,
        description,
      }),
    },
    {
      path: path.join(outDir, "index.js"),
      content: renderIndexJs({ integrationPackage }),
    },
    {
      path: path.join(outDir, "README.md"),
      content: renderReadme({ integration, integrationPackage }),
    },
  ];

  if (!opts.dryRun) {
    await mkdir(outDir, { recursive: true });
    for (const file of files) {
      await writeFile(file.path, file.content, "utf8");
    }
  }

  const configSnippet = renderConfigSnippet({ integration, outDir });

  return { path: outDir, configSnippet, files };
}

// ── Validation ──────────────────────────────────────────────────────────────

/**
 * Integration names need to be a safe directory name and safe npm package
 * identifier. We accept the same subset as npm package names' "simple"
 * form: lowercase alphanumerics, hyphen, underscore.
 */
function validateIntegrationName(name: string): string {
  if (!/^[a-z0-9][a-z0-9_-]*$/.test(name)) {
    throw new Error(
      `invalid integration name '${name}': must be lowercase alphanumeric with optional '-' or '_'`,
    );
  }
  return name;
}

// ── Templates ───────────────────────────────────────────────────────────────

function renderPackageJson(args: {
  integration: string;
  scaffoldVersion: string;
  integrationPackage: string;
  description: string;
}): string {
  const pkg = {
    name: `chorus-mcp-${args.integration}`,
    version: args.scaffoldVersion,
    description: args.description,
    type: "module",
    private: true,
    scripts: {
      start: "node index.js",
    },
    bin: {
      [`chorus-mcp-${args.integration}`]: "./index.js",
    },
    dependencies: {
      "@chorus/mcp": "^0.1.0",
      [args.integrationPackage]: "*",
    },
    engines: { node: ">=20" },
  };
  return JSON.stringify(pkg, null, 2) + "\n";
}

/**
 * Entrypoint is a plain .js file — no tsup, no TypeScript in the scaffold.
 * Keeps `npm install && node index.js` frictionless.
 */
function renderIndexJs(args: { integrationPackage: string }): string {
  return `#!/usr/bin/env node
/**
 * Chorus MCP server for ${args.integrationPackage}.
 * Generated by @chorus/mcp. Customize if you need a credential service;
 * the default is tool-exposure-only (credentials must be managed via
 * \`chorus credentials\` on the host running this MCP server).
 */
import { serveIntegration } from "@chorus/mcp/serve";
import integration from "${args.integrationPackage}";

serveIntegration({ integration }).catch((err) => {
  // Write to stderr so it lands in the MCP client's log rather than
  // getting swallowed by the stdio JSON-RPC stream.
  process.stderr.write(\`chorus-mcp fatal: \${err?.stack ?? err?.message ?? err}\\n\`);
  process.exit(1);
});
`;
}

function renderReadme(args: {
  integration: string;
  integrationPackage: string;
}): string {
  return `# chorus-mcp-${args.integration}

MCP server exposing the **${args.integration}** Chorus integration as a set of
callable tools. Generated by \`chorus mcp generate ${args.integration}\`.

## Install

\`\`\`bash
cd mcp-servers/chorus-${args.integration}
npm install
\`\`\`

## Run (standalone)

\`\`\`bash
npm start
\`\`\`

This starts an MCP server on stdio. Most users don't run it directly —
instead, they register it with their MCP client (Claude Desktop, Cursor,
Zed, etc.).

## Register with Claude Desktop

On macOS, edit \`~/Library/Application Support/Claude/claude_desktop_config.json\`.
On Windows, edit \`%APPDATA%\\\\Claude\\\\claude_desktop_config.json\`.

Add this under \`mcpServers\`:

\`\`\`json
{
  "mcpServers": {
    "chorus-${args.integration}": {
      "command": "node",
      "args": ["./mcp-servers/chorus-${args.integration}/index.js"],
      "cwd": "<absolute path to your Chorus project>"
    }
  }
}
\`\`\`

Restart Claude Desktop. The integration's operations appear as tools named
\`${args.integration}__<operation>\`.

## Register with Cursor

Edit your project's \`.cursor/mcp.json\`:

\`\`\`json
{
  "mcpServers": {
    "chorus-${args.integration}": {
      "command": "node",
      "args": ["./mcp-servers/chorus-${args.integration}/index.js"]
    }
  }
}
\`\`\`

## Register with Zed

Edit \`~/.config/zed/settings.json\` (macOS/Linux) or the equivalent on
Windows. Under \`context_servers\`:

\`\`\`json
{
  "context_servers": {
    "chorus-${args.integration}": {
      "command": "node",
      "args": ["./mcp-servers/chorus-${args.integration}/index.js"]
    }
  }
}
\`\`\`

## What gets exposed

Running \`tools/list\` against this server returns:

- \`${args.integration}__<operation>\` — one tool per integration operation
- \`${args.integration}__list_credentials\` — read-only, lists saved credentials
- \`${args.integration}__configure_<typeName>\` — one per credential type
- \`${args.integration}__authenticate\` — OAuth flow starter (when applicable)
- \`${args.integration}__test_auth\` — validates a stored credential

The four credential tools follow the \`docs/CREDENTIALS_ANALYSIS.md\` §7 contract.

## Security

- Credentials never leave the Chorus user's machine. The MCP server reads
  them via the runtime's credential service; plaintext never hits stdout.
- \`__test_auth\` MUST be read-only; if the integration wires a mutating
  operation as its test hook, the MCP server refuses and returns an error.
- This server inherits the Chorus threat model — same as running the
  integration via \`chorus run\`.

## Regeneration

If the integration adds or removes operations, regenerate:

\`\`\`bash
chorus mcp generate ${args.integration} --out mcp-servers/chorus-${args.integration}
\`\`\`

No handwritten code is lost: the scaffold is pure boilerplate; all tool
shape comes from the integration's manifest at runtime.
`;
}

/**
 * The config snippet users paste into their MCP client's config file. We
 * return it as a raw JSON string (pretty-printed) so callers can print it
 * directly in the CLI output.
 */
function renderConfigSnippet(args: {
  integration: string;
  outDir: string;
}): string {
  const rel = path
    .relative(process.cwd(), path.join(args.outDir, "index.js"))
    .replace(/\\/g, "/");
  const snippet = {
    mcpServers: {
      [`chorus-${args.integration}`]: {
        command: "node",
        args: [rel.startsWith(".") ? rel : `./${rel}`],
      },
    },
  };
  return JSON.stringify(snippet, null, 2) + "\n";
}
